#!/bin/bash
# Alternative deployment using EC2 Instance Connect
# This script helps setup SSH access when the original key pair is unavailable

EC2_IP="18.215.117.40"
EC2_USER="ubuntu"
DOMAIN="stocks.thatinsaneguy.com"

echo "========================================"
echo "Stock Gita - SSH Setup via Instance Connect"
echo "========================================"
echo ""
echo "The SSH key 'stock-gita-key.pem' cannot be retrieved from AWS."
echo "AWS only allows key pair download once at creation time."
echo ""
echo "OPTION 1: Use EC2 Instance Connect (Recommended)"
echo "---------------------------------------------"
echo "1. Go to: https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Instances:"
echo "2. Select instance: i-0778edb39981fbc46 (stock-gita-server)"
echo "3. Click 'Connect' button (top right)"
echo "4. Select 'EC2 Instance Connect' tab"
echo "5. Click 'Connect' to open browser-based terminal"
echo ""
echo "Once connected, run these commands to add your public SSH key:"
echo ""
echo "  # In the browser terminal:"
echo "  mkdir -p ~/.ssh"
echo "  chmod 700 ~/.ssh"
echo "  echo 'YOUR_PUBLIC_KEY_HERE' >> ~/.ssh/authorized_keys"
echo "  chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "To get your public key, run on your Mac:"
echo "  cat ~/.ssh/id_rsa.pub"
echo ""
echo "OR create a new key pair:"
echo "  ssh-keygen -t rsa -b 4096 -f ~/.ssh/stock_gita_key"
echo "  cat ~/.ssh/stock_gita_key.pub"
echo ""
echo ""
echo "OPTION 2: Create and Attach New Key Pair"
echo "---------------------------------------------"
echo "1. Create new key pair in AWS Console"
echo "2. Stop the instance"
echo "3. Detach root volume"
echo "4. Attach volume to temporary instance"
echo "5. Add new public key to authorized_keys"
echo "6. Reattach volume and restart"
echo ""
echo "(This is more complex - EC2 Instance Connect is easier)"
echo ""
echo "========================================"
echo ""
